### ISSUE TITLE
RaZberry card on remote Pi not seen by OZW

### ISSUE THREAD

**Issue by danielbrunt57** [OpenZWave/qt-openzwave#136]
I have a RaZberry card on a Pi which is available via ser2net at tcpip_addr:port_4000.  Why can ozw not see/use the device created by socat on my HASSIO platform?

**Comment by kpine** [comment]
Pass the device as a volume. Except if you're using the Addon you probably can't do that.

**Comment by kpine** [comment]
For a more detailed answer:

1. You're not going to get much support here for using network serial devices. See closed issue #79 for example.
2. Assuming you are using the OpenZWave Addon, the Home Assistant organization manages their own docker image for use with the addon. You'll need to ask them how you can configure the addon to use the socat device. I presume that is your problem (?), but you didn't give any details.
3. If you are able to run the Docker standalone images provided by OpenZWave, a user in the HA Discord has had initial success using a socat serial device. The solution was to pass in the socat device as a volume, not a device. You could try reading [these ](https://community.openhab.org/t/share-z-wave-dongle-over-ip-usb-over-ip-using-ser2net-socat-guide/34895/170) posts in the OpenHAB forum and see if that works for you. You're basically on your own though if it has issues...

**Comment by danielbrunt57** [comment]
Yes, I am trying/would like to use the HA OZW add-on.  
However, I did try the ozw docker standalone on the pi itself and while it seems to be be able to open the local physical port, it seems to not be able to communicate with the RaZberry...just a whole lot of nothing as compared to a spare HUSBZB-1 plugged into the pi as a test and I'm wondering if that could be because the RaZberry was/is configured in HomeSeer and perhaps needs a factory reset?  Before starting ozw on the pi I did disable Z-Wave in HS AND also terminated ser2net on the pi so that /dev/ttyAMA0 was free and clear.  I'm pretty sure I need to overcome that hurdle before trying ser2net...

The OpenHAB implementation of rfc2217://{ip_addr}:{ip_port} looks like it might be the way of the future in eliminating socat.  I hope OZW is looking at this!

**Comment by danielbrunt57** [comment]
So, I used Z-Way (on a separate SD card) to reset my RaZberry,  It was in SIS mode (something to do with HomeSeer?).  I disabled SUC/SIS mode, changed SD cards & started my OZW all-in-one docker on the Pi and it could then communicate with /dev/ttyAMA0.  I have successfully included 2 nodes now and HASS saw the remote ozwdaemon (via MQTT I presume) and the 2 devices now show in HA.  My first node was Monoprice RGB Controller and is unrecognized but the 2nd was Monoprice On/Off switch and it works.  Only 20 more to go...

**Comment by scyto** [comment]
@danielbrunt57 nice, i just got a RazBerry.  Do you have a write up you could share?  
Why zwave2mqtt in docker on the pi vs on the pi natively?
anything i should know in terms of using zwave me software?
(also you might want to close this issue :-) )

**Comment by danielbrunt57** [comment]
Z-Way software is not required.  I only had to use it to reset the controller after having used it with HomeSeer.
I'm not using zwave2mqtt in docker on Pi.  I am using OpenZWave Version 1.6.1545 / qt-openzwave Version 1.2.0 / QT Version 5.12.8 via `docker pull openzwave/ozwdaemon:allinone-latest`. I also have the Windows version of OZWAdmin ver 0.1.74 on my PC. It seemed the easiest and quickest way I've found to get/maintain/upgrade OpenZWave on a single-purpose, dedicated machine (my Pi) and also the closest to what you would have if you added the OpenZWave **add-on** into HA (all supervisor add-ons are docker containers in HA).  I run HA on my HP ProDesk where I have the Mosquitto broker add-on, the MQTT Mosquitto broker integration and the OpenZWave (Beta) integration.

```
docker run -d \
 --name ozw \
 --restart=unless-stopped \
 --security-opt seccomp=unconfined \
 --device=/dev/ttyAMA0 \
 -v /opt/ozw/config:/opt/ozw/config \
 -v /etc/localtime:/etc/localtime:ro \
 -e MQTT_SERVER="192.168.1.104" \
 -e MQTT_USERNAME="homeassistant" \
 -e MQTT_PASSWORD="A----#--V-#----#-----#---#---#E----------#C-----#T---H-----#---" \
 -e USB_PATH=/dev/ttyAMA0 \
 -e OZW_NETWORK_KEY=0x##,0x##,0x##,0x##,0x##,0x##,0x##,0x##,0x##,0x##,0x##,0x##,0x##,0x##,0x##,0x## \
 -p 1983:1983 \
 -p 5901:5901 \
 -p 7800:7800 \
openzwave/ozwdaemon:latest
```

**Comment by scyto** [comment]
Thanks, will give that a try too, will post back with a yaml  once i have converted it.

(i have zwave2mqtt working since i posted, found z-way and openzwave in that container hated sharing the serial port - no surprise!, also as i understand in zwave2mqtt is just a web interface to the latest openzwave?)

I had tried both openzwave and zwave2mqtt on a NAS with USB (where the HA and MQTT run too) but wanted to switch to a dedicated unit for z-wave.  What i liked about zwave2mqtt is it *appears* to have more of the zwave options around inclusion and multiple controllers i expected to see.  I couldn't see that in open zwave - but will keep looking! 

thanks for prompt response, I apprecaite it.

my draft yaml file (yes i know they have one on their guthub, i prefer mine with my changes)
```
version: '3.7'
services:
  openzwave:
    container_name: openzwave
    image: openzwave/ozwdaemon:latest
    security_opt:
      - seccomp:unconfined
    restart: unless-stopped
    tty: true
    stop_signal: SIGINT
    networks:
      - zwave
    devices:
      - '/dev/ttyAMA0:/dev/ttyAMA0'
    volumes:
      - ./config:/opt/ozw/config 
      - /etc/localtime:/etc/localtime:ro
    ports:
	  - '1983:1983'
   environment:
      MQTT_SERVER: "192.168.0.1"
      MQTT_USERNAME: "my-username"
      MQTT_PASSWORD: "my-password"
      USB_PATH: "/dev/ttyAMA0"
      OZW_NETWORK_KEY: "0x##,0x##,0x##,0x##,0x##,0x##,0x##,0x##,0x##,0x##,0x##,0x##,0x##,0x##,0x##,0x##"


networks:
  zwave:
# volumes:
#   openzwave:
#     name: openzwave
```
