### ISSUE TITLE
Fibaro FGWD111 Walli Dimmer malfunction

### ISSUE THREAD

**Issue by simulot** [OpenZWave/qt-openzwave#137]
Hi,

Let me know if this is the right place for opening the issue.

I used to use z-wave implementation provided by home assistant. Since I have moved the noisy nas to the basement, I have moved the zwave stack to a raspberry pi running a dockerized ozwdaemon and communicate to HA through  mqtt. 

It works as expected, except for all of 3 FGWD111 Walli Dimmers which aren't responsive. Before the move to ozwdaemon,  it was some latency, but it was tolerable.

- commands sent by HA take about 10+ seconds to be applied by devices if applied
- device feedback comes very late if it arrives.
- I can see there is a lot of traffic for the node when I send a command using HA, or directly by OZWAdmin.
- Changing the light level in OZWAdmin isn't more efficient.

Other devices are working great:
- Fibaro FGS212 Switch 3kW are very responsive, even for remote ones. 
- A bunch of battery powered door sensors, temperature and  motion detectors are also snappy.

The dimmers are powered on the main, and very closed to the zwave dongle. Other devices are doing well.  So, I don't think this is a problem with radio network. 

**Versions:**
USB dongle: UZB3 Z-Wave USB Adapter by Sigma Designs
OpenZWave Version 1.6.1232
qt-openzwave Version: 1.2.0
Docker image: 46506bc87a9dcb19222a3a222718e32db8ba1ed736d0a0c9d680e830d2fb0fd9
 
Let me know of to get OZWAdmin logs in a file.

Thanks a lot
++ simulot

**Comment by kpine** [comment]
Problem was an API incompatibility, fixed in HA. https://github.com/home-assistant/core/issues/38068

**Comment by simulot** [comment]
Thanks for the information.

Indeed, calling the turn_on service with transition = 0 works as intended. 
Apparently, the fix is on is way.  
Is it some workaround?

**Comment by simulot** [comment]
Here is my workaround while waiting the official release:
1- Create an helper script for setting the brightness of any light:
```
light_dimmer:
  alias: Light Dimmer
  max: 10
  mode: parallel
  fields:
    entity_id:
      description: The entity
      example: the id
    brightness:
      description: the desired brightness
      example: "128"
  sequence:
    - data_template:
        brightness: "{{ brightness }}"
        entity_id: "{{ entity_id }}"
        transition: 0
      service: light.turn_on
```

2 -Create an input_number helper that will be placed on the room card for each light
3- Create an automation to link the input_number to the actual light:
```
- id: '1596000897984'
  alias: Dimmer salon
  description: ''
  trigger:
  - entity_id: input_number.proxy_salon
    platform: state
  condition: []
  action:
  - data_template:
      brightness: '{{ states("input_number.proxy_salon") | int }}'
      entity_id: light.fgwd111_walli_dimmer_level
    service: script.light_dimmer
  mode: queued
  max: 10
```
